name: Deploy Firestore Rules to Production

on:
  push:
    branches:
      - main
    paths:
      - "firestore.rules"
      - ".github/workflows/deploy-firestore-rules-production.yml"

jobs:
  deploy:
    name: Deploy Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node

      - name: ğŸš€ Deploy to kavout
        uses: pchmn/firebase-cli-github-action@main
        with:
          packager: pnpm
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAVOUT_PROD }}
          projectId: kavout-da989
          args: deploy --only firestore:rules
