name: Deploy Firestore Rules to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "firestore.rules"
      - ".github/workflows/deploy-firestore-rules-dev.yml"

jobs:
  deploy:
    name: Deploy Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node

      - name: ğŸš€ Deploy to kavout-dev
        uses: pchmn/firebase-cli-github-action@main
        with:
          packager: pnpm
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAVOUT_DEV }}
          projectId: kavout-dev
          args: deploy --only firestore:rules
