name: Deploy Firebase Functions to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/functions/**"
      - ".github/workflows/deploy-functions-dev.yml"

jobs:
  test:
    name: ğŸ§ª Test Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: ğŸ— Create service account key file for tests
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT }}' > ${{ runner.temp }}/serviceAccountKey.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(echo ${{ runner.temp }}/serviceAccountKey.json)" >> $GITHUB_ENV

      - name: ğŸ§ª Test functions
        run: pnpm test:functions

  deploy:
    name: ğŸš€ Deploy Functions
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: ğŸ— Setup firebase CLI
        uses: pchmn/firebase-cli-github-action@main
        with:
          packager: pnpm
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAVOUT_DEV }}
          projectId: kavout-dev

      - name: ğŸš€ Deploy to kavout-dev
        run: pnpm deploy:functions
