name: Deploy Firebase Functions to Production

on:
  push:
    branches:
      - main
    paths:
    - "apps/functions/**"
    - ".github/workflows/deploy-functions-production.yml"

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: ğŸ— Setup firebase CLI
        uses: pchmn/firebase-cli-github-action@main
        with:
          packager: pnpm
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAVOUT_PROD }}
          projectId: kavout-da989

      - name: ğŸ— Create service account key file for tests
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT }}' > ${{ runner.temp }}/serviceAccountKeyTest.json
          echo "GOOGLE_APPLICATION_CREDENTIALS_TEST=$(echo ${{ runner.temp }}/serviceAccountKeyTest.json)" >> $GITHUB_ENV

      - name: ğŸ§ª Test functions
        run: pnpm test:functions:coverage

      - name: ğŸš€ Deploy to kavout
        run: pnpm deploy:functions
