name: Deploy Firebase Functions to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/functions/**"
      - ".github/workflows/deploy-functions-dev.yml"

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node

      - name: ğŸ— Setup firebase CLI
        uses: pchmn/firebase-cli-github-action@main
        with:
          packager: pnpm
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAVOUT_DEV }}
          projectId: kavout-dev

      - name: ğŸš€ Deploy to kavout-dev
        run: pnpm deploy:functions

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: functions-dist
