name: Deploy Lambda Functions to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/functions/**"
      - "packages/core/**"
      - ".github/workflows/deploy-functions-dev.yml"

jobs:
  changes:
    name: ðŸ“‚ Check for changes
    runs-on: ubuntu-latest
    outputs:
      shouldRun: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v37
        id: filter
        with:
          since_last_remote_commit: true
          files: |
            apps/functions/**
            packages/core/**
            .github/workflows/deploy-functions-dev.yml
            pnpm-lock.yaml

  deploy:
    name: ðŸš€ Deploy Functions
    needs: changes
    if: needs.changes.outputs.shouldRun == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ðŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true
          turbo-cache: true

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: ðŸš€ Deploy functions to kuzpot-dev
        working-directory:  apps/functions
        run: pnpm deploy:dev

      # - name: ðŸ— Setup firebase CLI
      #   uses: pchmn/firebase-cli-github-action@main
      #   with:
      #     packager: pnpm
      #     serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
      #     projectId: kuzpot-dev

      # - name: ðŸ— Create service account key file for tests
      #   run: |
      #     echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT }}' > ${{ runner.temp }}/serviceAccountKeyTest.json
      #     echo "GOOGLE_APPLICATION_CREDENTIALS_TEST=$(echo ${{ runner.temp }}/serviceAccountKeyTest.json)" >> $GITHUB_ENV

      # - name: ðŸ§ª Test functions
      #   run: pnpm test:functions:coverage
      #   env:
      #     TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}

      # - name: â™»ï¸ Create env file
      #   working-directory:  apps/functions
      #   run: |
      #     touch .env
      #     echo BETTERSTACK_TOKEN=${{ secrets.BETTERSTACK_TOKEN_DEV }} >> .env
      #     cat .env

      # - name: ðŸš€ Deploy to kuzpot-dev
      #   run: pnpm deploy:functions

      # - run: rm apps/functions/.env
