name: Deploy Firebase Functions to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/functions/**"
      - ".github/workflows/deploy-functions-dev.yml"

jobs:
  build:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: ğŸ”¨ Build
        run: pnpm build:functions

      - uses: actions/upload-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist/

  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          keep-npmrc: false

      - name: ğŸ“¦ Remove local dependencies
        working-directory: apps/functions
        run: pnpm remove -D @judgeme/tsconfig eslint-config-judgeme-ts

      - name: ğŸš€ Deploy to judgeme-dev
        uses: ./.github/actions/setup-firebase-tools
        with:
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JUDGEMEV2_DEV }}
          projectId: judgemev2-dev
          args: deploy --only functions

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: functions-dist
