name: Deploy Firebase Functions to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/functions/**"
      - ".github/workflows/deploy-functions-dev.yml"

jobs:
  build:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: ğŸ”¨ Build
        working-directory: apps/functions
        run: pnpm build:rollup

      - uses: actions/upload-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist/

  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: functions-dist
          path: apps/functions/dist

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node

      - name: ğŸ“¦ Remove local dependencies
        working-directory: apps/functions
        run: pnpm remove -D @kavout/tsconfig eslint-config-kavout-ts

      - name: ğŸš€ Deploy to kavout-dev
        uses: pchmn/firebase-cli-github-action@main
        with:
          packager: pnpm
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAVOUT_DEV }}
          projectId: kavout-dev
          args: deploy --only functions --debug

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: functions-dist
