name: Publish Mobile App Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/mobile/**"
      - "packages/react-native/**"
      - ".github/workflows/publish-mobile-preview.yml"

jobs:
  changes:
    name: ðŸ“‚ Check for changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          mobile:
            - "apps/mobile/**"
            - "packages/react-native/**"
            - ".github/workflows/publish-mobile-preview.yml"

  publish:
    needs: changes
    if: needs.changes.outputs.mobile == 'true'
    name: Publish Mobile App Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: ðŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true
          metro-cache: true

      - name: ðŸ— Setup expo
        uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸ’¬ Get eas update message
        id: update-message
        run: echo "value=$(git show -s --format=%s)" >> $GITHUB_OUTPUT

      - name: ðŸš€ Publish eas update
        working-directory: apps/mobile
        run: eas update --branch ${{ github.head_ref }} --message "${{ steps.update-message.outputs.value }}"
