name: Publish Mobile App Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/mobile/**"
      - ".github/workflows/publish-mobile-preview.yml"

jobs:
  publish:
    name: Publish Mobile App Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ— Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true

      - name: ğŸ— Setup expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # - name: ğŸ—‚ï¸ Get native code changed files
      #   id: native-code-changed-files
      #   uses: tj-actions/changed-files@v35
      #   with:
      #     files: |
      #       apps/mobile/android/**
      #       apps/mobile/ios/**

      - name: ğŸš€ Create eas development build
        working-directory: apps/mobile
        run: eas build --non-interactive --wait --profile development --platform android

      # - name: ğŸš€ Publish expo go preview
      #   working-directory: apps/mobile
      #   run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: ğŸš€ Publish eas update
        working-directory: apps/mobile
        run: eas update --branch ${{ github.head_ref }} --message "PR ${{ github.event.number }} - ${{ github.event.pull_request.title }}"

      # - name: ğŸ’¬ Comment preview
      #   uses: expo/expo-github-action/preview-comment@v7
      #   with:
      #     project: apps/mobile
      #     channel: pr-${{ github.event.number }}
